spring:
  datasource:
    url: jdbc:h2:mem:urlcropdb
    # If you want to save to a file
    #    url: jdbc:h2:file:/data/urlcropdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
